
main: Facilitation main.cpp
	g++ -std=c++11 -Wall -pedantic -g Facilitation.cpp main.cpp

Facilitation: Facilitation.cpp Facilitation.hpp
	g++ -std=c++11 -Wall -pedantic -c Facilitation.cpp -o Facilitation.o
