# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_parameter <- function(times, num_stages, parameters, dispersal, interactions, init, w = 100, h = 100, bcond = 1L, dkernel = 1L) {
    .Call('facilitation_test_parameter', PACKAGE = 'facilitation', times, num_stages, parameters, dispersal, interactions, init, w, h, bcond, dkernel)
}

