# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_basic <- function(filename, outfilename = "") {
    .Call('facilitation_test_basic', PACKAGE = 'facilitation', filename, outfilename)
}

test_parameter <- function(times, num_stages, parameters, f, init, w = 10, h = 10) {
    .Call('facilitation_test_parameter', PACKAGE = 'facilitation', times, num_stages, parameters, f, init, w, h)
}

