# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_basic <- function(filename, outfilename = "") {
    .Call('facilitation_test_basic', PACKAGE = 'facilitation', filename, outfilename)
}

test_parameter <- function(times, num_stages, parameters, f, w, h, init) {
    .Call('facilitation_test_parameter', PACKAGE = 'facilitation', times, num_stages, parameters, f, w, h, init)
}

Random <- function(max) {
    .Call('facilitation_Random', PACKAGE = 'facilitation', max)
}

Bernoulli <- function(p) {
    .Call('facilitation_Bernoulli', PACKAGE = 'facilitation', p)
}

Exponential <- function(r) {
    .Call('facilitation_Exponential', PACKAGE = 'facilitation', r)
}

RandomSign <- function() {
    .Call('facilitation_RandomSign', PACKAGE = 'facilitation')
}

